#!/bin/sh

#		 _ _                                 _ _              
#		(_) |__  _   _ ___       _   _ _ __ (_) | _____ _   _ 
#		| | '_ \| | | / __|_____| | | | '_ \| | |/ / _ \ | | |
#		| | |_) | |_| \__ \_____| |_| | | | | |   <  __/ |_| |
#		|_|_.__/ \__,_|___/      \__,_|_| |_|_|_|\_\___|\__, |
#														|___/ 

engine="$(ibus engine)"

if [ "$engine" = "xkb:us::eng" ]; then
	ibus engine Unikey
else
	ibus engine xkb:us::eng
fi

refbar
