#!/bin/sh

#					  _     _     _  __ _   
#		 _ __ ___  __| |___| |__ (_)/ _| |_ 
#		| '__/ _ \/ _` / __| '_ \| | |_| __|
#		| | |  __/ (_| \__ \ | | | |  _| |_ 
#		|_|  \___|\__,_|___/_| |_|_|_|  \__|
#	


#day:   from start to end,
#night: from end to start.
start=6
end=18
day=6200
night=2400

run(){
	while true; do
		hour=date "+%H"
		if [ "$hour" -ge "$start" -a "$hour" -lt "$end" ]; then
			redshift -P -O "$day"
		else
			redshift -P -O "$night"
		fi
		sleep 3600
	done
}

run
