#!/bin/sh

#wget
#wget dl.suckless.org/dwm/dwm-6.2.tar.gz
cd $HOME/Downloads

# install dwm
#git clone /your edition/

#wget dl.suckless.org/st/st-0.8.2.tar.gz

cd $HOME
#install st
#git clone //

#install firefox, xbindkey, ibus-unikey, feh, xbacklight, xcompmgr, alpha st, intellj, libra office, redshift 

cd $HOME
git clone https://github.com/ILoveCodeAF/my_customize_dwm.git

src='my_customize_dwm'
des='/etc/wpa-supplicant/'
cp $src/wpa_supplicant.conf $des

des='/etc/X11/xorg.conf.d/'
cp $src/30-touchpad.conf $des

mkdir -p $HOME/.local/bin
des='$HOME/.local/bin/'
cp $src/dwmbar $des
cp $src/refbar $des
cp $src/ibus-unikey $des

des=$HOME
cp $src/.bashrc $des
cp $src/.bash_profile $des
cp $src/.xprofile $des
cp $src/.xinitrc $des
cp $src/.xbindkeysrc $des

